DROP DATABASE IF EXISTS `esgi-webapi`;

CREATE DATABASE `esgi-webapi` CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE albums(
    userID INTEGER NOT NULL,
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(25) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE comments(
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    firstName VARCHAR(25) NOT NULL,
    lastName VARCHAR(25) NOT NULL,
    email VARCHAR(50) NOT NULL,
    body TEXT NOT NULL,
    postID INTEGER NOT NULL REFERENCES posts(id)
) ENGINE=InnoDB;

CREATE TABLE photos(
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(50) NOT NULL,
    webURL VARCHAR(100) NOT NULL,
    albumID INTEGER NOT NULL REFERENCES albums(id),
    thumbnailURL VARCHAR(100) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE posts(
    userID INTEGER NOT NULL REFERENCES users(id),
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(50) NOT NULL,
    body TEXT NOT NULL
) ENGINE=InnoDB;

CREATE TABLE todos(
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    userID INTEGER NOT NULL REFERENCES users(id),
    title VARCHAR(50) NOT NULL,
    completed BOOLEAN DEFAULT FALSE
) ENGINE=InnoDB;

CREATE TABLE users(
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    firstName VARCHAR(25) NOT NULL,
    lastName VARCHAR(25) NOT NULL,
    username VARCHAR(15) NOT NULL,
    email VARCHAR(50) NOT NULL,
    phone VARCHAR(15) NOT NULL,
    website VARCHAR(100) NOT NULL
) ENGINE=InnoDB;
