DROP DATABASE IF EXISTS `esgi-webapi`;

CREATE DATABASE `esgi-webapi` CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE albums(
    userID INTEGER NOT NULL,
    id INTEGER PRIMARY KEY AUTO_INCREMENT
) ENGINE=InnoDB;

CREATE TABLE comments(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    firstName VARCHAR(25) NOT NULL,
    lastName VARCHAR(25) NOT NULL,
    email VARCHAR(50) NOT NULL,
    body TEXT NOT NULL,
    postID INTEGER NOT NULL
) ENGINE=InnoDB;

CREATE TABLE photos(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(50) NOT NULL,
    webURL VARCHAR(255) NOT NULL,
    albumID INTEGER NOT NULL,
    thumbnailURL VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE posts(
    userID INTEGER NOT NULL,
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(50) NOT NULL,
    body TEXT NOT NULL
) ENGINE=InnoDB;

CREATE TABLE todos(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    userID INTEGER NOT NULL,
    title VARCHAR(50) NOT NULL,
    completed BOOLEAN NOT NULL
) ENGINE=InnoDB;

CREATE TABLE users(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    firstName VARCHAR(25) NOT NULL,
    lastName VARCHAR(25) NOT NULL,
    username VARCHAR(15) NOT NULL,
    email VARCHAR(50) NOT NULL,
    phone VARCHAR(15) NOT NULL,
    website VARCHAR(255) NOT NULL
) ENGINE=InnoDB;
